[package]
name = "forge-core"
version = "0.1.0"
edition = "2024"
description = "Core artifact generation logic for nest-forge"
license = "MIT"

[dependencies]
thiserror.workspace = true
serde.workspace = true
heck.workspace = true
tracing.workspace = true
forge-template = { path = "../forge-template" }
forge-config = { path = "../forge-config" }
edit-distance = "2"

[dev-dependencies]
tempfile.workspace = true
insta = { workspace = true}
proptest = { workspace = true}
