[package]
name = "forge"
version = "0.1.0"
edition = "2024"
description = "A NestJS artifact generator CLI tool, built with Rust"
license = "MIT"
repository = "https://github.com/Boluwatife-AJB/nest-forge"
homepage = "https://github.com/Boluwatife-AJB/nest-forge"

keywords = ["nestjs", "codegen", "cli", "typescript", "scaffold"]
categories = ["command-line-utilities", "development-tools"]
exclude = [
    "tests/",
    ".github/",
]
rust-version.workspace = true

[[bin]]
name="forge"
path="src/main.rs"

[dependencies]
forge-core = { path = "../forge-core" }
forge-template = { path = "../forge-template" }
forge-config = { path = "../forge-config" }
clap.workspace = true
clap_complete = { workspace = true }
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
console.workspace = true
serde.workspace = true
serde_json.workspace = true
supports-color = { workspace = true }